In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
import json
import uuid
from confluent_kafka import Consumer, KafkaError

def read_kafka_topic_to_df(topic: str, bootstrap_servers: str, timeout_sec: float = 5.0) -> pd.DataFrame:
    """
    Вичитує всі доступні повідомлення з Kafka топіку в pandas DataFrame 
    без збереження оффсетів (не відмічаючи як прочитані).
    """
    conf = {
        'bootstrap.servers': bootstrap_servers,
        'group.id': f'pandas_analyzer_{uuid.uuid4()}', 
        'auto.offset.reset': 'earliest',
        'enable.auto.commit': False,
    }

    consumer = Consumer(conf)
    
    try:
        consumer.subscribe([topic])
        print(f"Підписано на топік: {topic}. Починаю вичитування...")
        
        data = []
        
        while True:
            msg = consumer.poll(timeout=timeout_sec)
            
            if msg is None:
                print(f"Немає нових повідомлень протягом {timeout_sec} сек. Завершення читання.")
                break
                
            if msg.error():
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    continue
                else:
                    print(f"Помилка Kafka: {msg.error()}")
                    break

            try:
                value_str = msg.value().decode('utf-8')
                value_dict = json.loads(value_str)
                data.append(value_dict)
            except Exception as e:
                print(f"Помилка декодування: {e}")

    finally:
        consumer.close()
        print(f"Консьюмер закрито. Всього вичитано повідомлень: {len(data)}")

    return pd.DataFrame(data)

In [19]:
bootstrap_servers = 'localhost:19092'
topic = 'news-parsed'

df = read_kafka_topic_to_df(bootstrap_servers=bootstrap_servers, topic=topic)
df.head()

Підписано на топік: news-parsed. Починаю вичитування...
Немає нових повідомлень протягом 5.0 сек. Завершення читання.
Консьюмер закрито. Всього вичитано повідомлень: 7754

,title,description,link,image_url,published_at,source_id
0,росіяни вночі вдарили по Дніпру балістикою є п...,росіяни вночі вдарили по Дніпру балістикою є п...,https://unn.ua/news/rosiiany-vnochi-vdaryly-po...,https://unn.ua/img/2026/04/16/1776300112-1832-...,2026-04-16T00:41:56Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1
1,"Інфантіно заявив, що Іран візьме участь у чемп...","Інфантіно заявив, що Іран візьме участь у чемп...",https://unn.ua/news/infantino-zaiavyv-shcho-ir...,https://unn.ua/img/2026/04/15/1776293154-1132-...,2026-04-15T22:45:57Z,8fbd6207-4ebc-4b96-93c8-8197ee3925e1
2,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,https://unn.ua/news/ataky-rf-na-dnipro-15-kvit...,https://unn.ua/img/2026/04/15/1776252519-2000-...,2026-04-15T11:28:42Z,9469aa98-da2f-4b40-b98d-db991ca85f51
3,Amazon представила авіаційну антену супутников...,Антена на літаку дає доступ до альтернативи St...,https://ua.korrespondent.net/tech/technews/487...,https://kor.ill.in.ua/m/190x120/4402706.jpg,2026-04-14T12:57:00Z,1f37bd0e-7185-48e2-8124-718a201e98c9
4,"""Українська бронетехніка"" модернізує ударні др...","""Українська бронетехніка"" модернізує ударні др...",https://unn.ua/news/ukrainska-bronetekhnika-mo...,https://unn.ua/img/2026/04/15/1776292651-3940-...,2026-04-15T22:37:33Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7754 entries, 0 to 7753
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         7754 non-null   str
 1   description   7754 non-null   str
 2   link          7754 non-null   str
 3   image_url     6180 non-null   str
 4   published_at  7749 non-null   str
 5   source_id     7754 non-null   str
dtypes: str(6)
memory usage: 363.6 KB

In [21]:
import os
from dotenv import load_dotenv

env_path = os.path.abspath('../.env')
load_dotenv(dotenv_path=env_path)

ADMIN_TOKEN = os.getenv('ADMIN_TOKEN')
API_URL = os.getenv('API_URL')
API_URL

'http://localhost:5000/api/v1'

In [25]:
ADMIN_TOKEN

'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijc5NTRlYzU4ODgxNmVjNDIifQ.eyJ1c2VybmFtZSI6ImFuZHJleWhvaG90dmEyIiwic3ViIjoiMzBmZjUxM2QtOTRjMy00MDk2LWFiZmItMmExN2E0ZjVjZjdkIiwicm9sZSI6IkFETUlOIiwiZW1haWwiOiJhbmRyZXlob2hvdHZhMkBnbWFpbC5jb20iLCJpYXQiOjE3NzY3MjkwNTIsImV4cCI6MTc3NjczMjY1Mn0.Kr2kP4z4m8s65ouLfkXeka4bWpvPpdij8xlJSnCRFHMy72xUyiCcrzhC6SHDj7yYVtfMcawBU1RYAj_P_A2fK4EJHXUmvaLo-ezlRVYmKzpZL7vZR8qQTi4mm1eUq3ys6k8n1Mp-YfJzwumZqxLlBUJLRDDYIVrLQt-AN_6cubFUm0yAJLfZmlUVu86KUB5pZryVTXtk9XiqRm0-Lm9zu_HLw1LNC-HkNnHjEmgnRELxBFQ0UbzWZDU4Bun16AKW6_dJUKwZ_pTYJQwHa5S9rN2O-L2oYkLZQjTR2SiDDtbBqHOkq9Or2-oO6GASkVxlhcaZsnbq64zitZ1zteRm_g'

In [23]:
categories = ['Війна', 'Політика', 'Економіка', 'Технології', 'Наука', 'Освіта', 'Спорт', 'Культура', 'Здоров\'я', 'Туризм']
categories

['Війна',
 'Політика',
 'Економіка',
 'Технології',
 'Наука',
 'Освіта',
 'Спорт',
 'Культура',
 "Здоров'я",
 'Туризм']

In [29]:
import requests

headers = {
    'Authorization': f'Bearer {ADMIN_TOKEN}',
}

category_mapping = {}

for category in categories:
    r = requests.get(
        f'{API_URL}/sources',
        params={
            'pageSize': 1000,
            'search': category,
        },
        headers=headers,
    )
    res = r.json()
    print(res)
    for item in res['data']:
        if item['id'] not in category_mapping:
            category_mapping[item['id']] = category
    print(f'Категорія {category} оброблена: {res['totalCount']} нових джерел')

print(f'Розмір словника джерел: {len(category_mapping)}')

{'data': [{'id': '07c61aaf-5390-46c9-82ff-6a202f519a65', 'name': '24 канал - Війна', 'url': 'https://24tv.ua/military/military-24_tag12132/', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:45:01.45573Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://24tv.ua/assets/sites/military/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:01.45573Z'}, {'id': '259d5e7e-bb10-4d20-a03c-bdee65ee9166', 'name': 'Obozrevatel - Війна', 'url': 'https://www.obozrevatel.com/ukr/topic/vojna-v-ukraine-2022/', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:45:15.616704Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://cdn.obozrevatel.com/news/img/favicons/favicon.ico', 'createdAt': '2026-04-16T20:00:51.380764Z', 'updatedAt': '2026-04-21T12:45:15.616704Z'}, {'id': '4080df74-7d07-44ec-822e-8177131b6b5e', 'name': 'Главком - Війна', 'url': 'https://glavcom.ua/topics/donbas.html', 'type': 'HTML', 'active': True, 'schedule': '1 * * * *', 'lastParsedAt': '2026-04-21T12:44:57.433835Z', 'nextRunAt': '2026-04-21T13:01:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:36:26.574031Z', 'updatedAt': '2026-04-21T12:44:57.433835Z'}, {'id': '6cdf1e5f-0fc7-48b1-a797-126f96b330d1', 'name': 'УНН - Війна', 'url': 'https://unn.ua/rss/war_uk.xml', 'type': 'RSS', 'active': True, 'schedule': '*/30 * * * *', 'lastParsedAt': '2026-04-21T12:44:51.364773Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://unn.ua/social_logo.jpg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:51.364773Z'}, {'id': '7062dead-566b-4734-a803-256c1de37080', 'name': 'Уніан - Війна', 'url': 'https://www.unian.ua/war', 'type': 'HTML', 'active': True, 'schedule': '*/30 * * * *', 'lastParsedAt': '2026-04-21T12:44:34.181176Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://www.unian.ua/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:34.181176Z'}, {'id': '7503e5bf-5ebc-44ef-b892-1f621ddf79a8', 'name': 'ТСН - Війна', 'url': 'https://tsn.ua/ato', 'type': 'HTML', 'active': True, 'schedule': '0 */1 * * *', 'lastParsedAt': '2026-04-21T12:44:36.202782Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://tsn.ua/favicon.svg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:36.202782Z'}, {'id': '81039aff-e291-4363-a16c-632b0531ae54', 'name': 'Інтерфакс Україна - ВІйна', 'url': 'https://interfax.com.ua/news/tag/%D0%B2%D1%96%D0%B9%D0%BD%D0%B0.html', 'type': 'HTML', 'active': True, 'schedule': '9 * * * *', 'lastParsedAt': '2026-04-21T12:45:51.994863Z', 'nextRunAt': '2026-04-21T13:09:00Z', 'logoUrl': 'https://interfax.com.ua/static/favicon.png', 'createdAt': '2026-04-16T14:25:53.773927Z', 'updatedAt': '2026-04-21T12:45:51.994863Z'}, {'id': 'cf39026f-33a0-485a-b7c1-8dde2aaca692', 'name': 'BBC News - Війна', 'url': 'https://www.bbc.com/ukrainian/topics/czp6w66edqpt', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:44:58.442376Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://static.files.bbci.co.uk/ws/simorgh-assets/public/ukrainian/images/icons/icon-192x192.png', 'createdAt': '2026-04-16T19:20:39.149301Z', 'updatedAt': '2026-04-21T12:44:58.442376Z'}, {'id': 'e0df0c62-bcac-484c-bbb9-3dd52d357421', 'name': 'УкрІнформ - Війна', 'url': 'https://www.ukrinform.ua/rubric-ato/block-lastnews', 'type': 'HTML', 'active': True, 'schedule': '*/30 * * * *', 'lastParsedAt': '2026-04-21T12:44:36.204185Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://www.ukrinform.ua/img/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:36.204185Z'}], 'totalCount': 9, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Війна оброблена: 9 нових джерел
{'data': [{'id': '07175fc3-b4c1-4417-b583-bbb72877aeed', 'name': 'Уніан - Політика', 'url': 'https://www.unian.ua/politics', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:44:58.441202Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://www.unian.ua/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:58.441202Z'}, {'id': '07b32718-8ecb-4130-ab88-345070fbb70a', 'name': 'УНН - Політика', 'url': 'https://unn.ua/rss/politics_uk.xml', 'type': 'RSS', 'active': True, 'schedule': '0 * * * *', 'lastParsedAt': '2026-04-21T12:44:42.271531Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://unn.ua/social_logo.jpg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:42.271531Z'}, {'id': '30a4c6bb-1fa5-4a82-b054-161031431d4b', 'name': 'LB - Політика', 'url': 'https://lb.ua/rss/ukr/politics.xml', 'type': 'RSS', 'active': True, 'schedule': '0 * * * *', 'lastParsedAt': '2026-04-21T12:44:39.243273Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': None, 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:39.243273Z'}, {'id': '465c1bd9-90b1-45e9-8235-e9897d39d51c', 'name': 'Obozrevatel - Політика', 'url': 'https://www.obozrevatel.com/ukr/politics-news/', 'type': 'HTML', 'active': True, 'schedule': '11 * * * *', 'lastParsedAt': '2026-04-21T12:45:56.035152Z', 'nextRunAt': '2026-04-21T13:11:00Z', 'logoUrl': 'https://cdn.obozrevatel.com/news/img/favicons/favicon.ico', 'createdAt': '2026-04-16T20:03:18.2623Z', 'updatedAt': '2026-04-21T12:45:56.035152Z'}, {'id': '6630f1ab-461a-4d4c-a786-58accbd8a636', 'name': 'Главком - Політика 2', 'url': 'https://glavcom.ua/world/world-politics.html', 'type': 'HTML', 'active': True, 'schedule': '11 * * * *', 'lastParsedAt': '2026-04-21T12:46:06.132398Z', 'nextRunAt': '2026-04-21T13:11:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:41:24.770404Z', 'updatedAt': '2026-04-21T12:46:06.132398Z'}, {'id': '7c869d1a-952e-40de-8018-9b541e3b58c0', 'name': 'ТСН - Політика', 'url': 'https://tsn.ua/politika', 'type': 'HTML', 'active': True, 'schedule': '*/30 * * * *', 'lastParsedAt': '2026-04-21T12:44:32.159153Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'https://tsn.ua/favicon.svg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:32.159153Z'}, {'id': 'a4b0d847-fc7e-4c91-95a3-5c6b17eda13d', 'name': 'Корреспондент - Політика', 'url': 'http://k.img.com.ua/rss/ua/politics.xml', 'type': 'RSS', 'active': True, 'schedule': '14 * * * *', 'lastParsedAt': '2026-04-21T12:46:41.225562Z', 'nextRunAt': '2026-04-21T13:14:00Z', 'logoUrl': 'http://news.img.com.ua/img/smalllogo.gif', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:46:41.225562Z'}, {'id': 'a7d37dcd-1de9-4bb7-ad39-1694e23d00b3', 'name': 'УкрІнформ - Політика', 'url': 'https://www.ukrinform.ua/rubric-polytics/block-lastnews', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:45:07.517047Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://www.ukrinform.ua/img/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:07.517047Z'}, {'id': 'b10290ea-b935-4f5c-b9bf-9b28cfc68cb5', 'name': 'Главком - Політика', 'url': 'https://glavcom.ua/country/politics.html', 'type': 'HTML', 'active': True, 'schedule': '10 * * * *', 'lastParsedAt': '2026-04-21T12:45:55.018713Z', 'nextRunAt': '2026-04-21T13:10:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:41:06.983774Z', 'updatedAt': '2026-04-21T12:45:55.018713Z'}, {'id': 'd9663e47-67c5-44c0-b5d0-124a6b949e63', 'name': 'Інтерфакс Україна - Політика', 'url': 'https://interfax.com.ua/news/political.html', 'type': 'HTML', 'active': True, 'schedule': '1 * * * *', 'lastParsedAt': '2026-04-21T12:44:54.405576Z', 'nextRunAt': '2026-04-21T13:01:00Z', 'logoUrl': 'https://interfax.com.ua/static/favicon.png', 'createdAt': '2026-04-16T14:20:50.633195Z', 'updatedAt': '2026-04-21T12:44:54.405576Z'}, {'id': 'df3b59a3-fa01-4279-bd1b-5041668f1966', 'name': '24 канал - Політика', 'url': 'https://24tv.ua/geopolitics/golovni-novini_tag11501/', 'type': 'HTML', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:44:57.436407Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://24tv.ua/assets/sites/geopolitics/favicon.ico', 'createdAt': '2026-04-16T13:12:57.6333Z', 'updatedAt': '2026-04-21T12:44:57.436407Z'}], 'totalCount': 11, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Політика оброблена: 11 нових джерел
{'data': [{'id': '06f45ce1-d8ee-4b3f-b9dc-415c12e42fc7', 'name': 'УкрІнформ - Економіка', 'url': 'https://www.ukrinform.ua/rubric-economy/block-lastnews', 'type': 'HTML', 'active': True, 'schedule': '4 * * * *', 'lastParsedAt': '2026-04-21T12:45:29.778994Z', 'nextRunAt': '2026-04-21T13:04:00Z', 'logoUrl': 'https://www.ukrinform.ua/img/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:29.778994Z'}, {'id': '0ef0188f-5b25-4689-b634-fe3e01135fa1', 'name': 'Корреспондент - Економіка', 'url': 'http://k.img.com.ua/rss/ua/economics.xml', 'type': 'RSS', 'active': True, 'schedule': '8 * * * *', 'lastParsedAt': '2026-04-21T12:45:39.890878Z', 'nextRunAt': '2026-04-21T13:08:00Z', 'logoUrl': 'http://news.img.com.ua/img/smalllogo.gif', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:39.890878Z'}, {'id': '237e2213-348c-48d2-bce9-6495565834e7', 'name': 'УНН - Економіка', 'url': 'https://unn.ua/rss/economics_uk.xml', 'type': 'RSS', 'active': True, 'schedule': '2 * * * *', 'lastParsedAt': '2026-04-21T12:45:13.598405Z', 'nextRunAt': '2026-04-21T13:02:00Z', 'logoUrl': 'https://unn.ua/social_logo.jpg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:13.598405Z'}, {'id': '3b3748dd-a7da-4596-b1f0-a1c7b47ccec4', 'name': 'Главком - Економіка', 'url': 'https://glavcom.ua/economics/finances.html', 'type': 'HTML', 'active': True, 'schedule': '3 * * * *', 'lastParsedAt': '2026-04-21T12:45:06.503588Z', 'nextRunAt': '2026-04-21T13:03:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:38:25.775729Z', 'updatedAt': '2026-04-21T12:45:06.503588Z'}, {'id': '71d38993-8c24-4f05-a94c-65e431c01dca', 'name': 'Obozrevatel - Економіка', 'url': 'https://www.obozrevatel.com/ukr/ekonomika-glavnaya/', 'type': 'HTML', 'active': True, 'schedule': '9 * * * *', 'lastParsedAt': '2026-04-21T12:45:49.971762Z', 'nextRunAt': '2026-04-21T13:09:00Z', 'logoUrl': 'https://cdn.obozrevatel.com/news/img/favicons/favicon.ico', 'createdAt': '2026-04-16T20:02:41.479179Z', 'updatedAt': '2026-04-21T12:45:49.971762Z'}, {'id': '7aac7fdb-ed17-4e98-8fa4-a60fe806f05e', 'name': 'ТСН - Економіка', 'url': 'https://tsn.ua/groshi', 'type': 'HTML', 'active': True, 'schedule': '3 */1 * * *', 'lastParsedAt': '2026-04-21T12:45:06.636075Z', 'nextRunAt': '2026-04-21T13:03:00Z', 'logoUrl': 'https://tsn.ua/favicon.svg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:06.636075Z'}, {'id': '9e22d20c-12c7-46c5-b035-99e360382051', 'name': '24 канал - Економіка', 'url': 'https://24tv.ua/rss/all.xml?googleFlg=true&tagId=4638', 'type': 'RSS', 'active': True, 'schedule': '5 * * * *', 'lastParsedAt': '2026-04-21T12:45:27.758463Z', 'nextRunAt': '2026-04-21T13:05:00Z', 'logoUrl': None, 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:27.758463Z'}, {'id': 'a5b97375-f1e7-4111-84c4-7f2a9c66ab3b', 'name': 'Інтерфакс Україна - Економіка', 'url': 'https://interfax.com.ua/news/economic.html', 'type': 'HTML', 'active': True, 'schedule': '3 * * * *', 'lastParsedAt': '2026-04-21T12:45:15.617569Z', 'nextRunAt': '2026-04-21T13:03:00Z', 'logoUrl': 'https://interfax.com.ua/static/favicon.png', 'createdAt': '2026-04-16T14:23:36.35521Z', 'updatedAt': '2026-04-21T12:45:15.617569Z'}, {'id': 'c11102c0-37cc-41b0-9ca4-577792cdffbc', 'name': 'Уніан - Економіка', 'url': 'https://www.unian.ua/economics', 'type': 'HTML', 'active': True, 'schedule': '4 * * * *', 'lastParsedAt': '2026-04-21T12:45:09.61484Z', 'nextRunAt': '2026-04-21T13:04:00Z', 'logoUrl': 'https://www.unian.ua/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:09.61484Z'}, {'id': 'c8ba437d-682a-41d7-be3f-7a59d2efcfa0', 'name': 'LB - Економіка', 'url': 'https://lb.ua/rss/ukr/economics.xml', 'type': 'RSS', 'active': True, 'schedule': '1 * * * *', 'lastParsedAt': '2026-04-21T12:44:55.421583Z', 'nextRunAt': '2026-04-21T13:01:00Z', 'logoUrl': None, 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:55.421583Z'}], 'totalCount': 10, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Економіка оброблена: 10 нових джерел
{'data': [{'id': '03be877b-ce1d-49b0-9e54-857cdfab1f38', 'name': '24 канал - Технології', 'url': 'https://24tv.ua/tech/tehno-golovni-novini_tag6220/', 'type': 'HTML', 'active': True, 'schedule': '24 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.676446Z', 'nextRunAt': '2026-04-21T13:24:00Z', 'logoUrl': 'https://24tv.ua/assets/sites/tech/favicon.ico', 'createdAt': '2026-04-16T13:50:59.161481Z', 'updatedAt': '2026-04-21T12:49:35.676446Z'}, {'id': '1f37bd0e-7185-48e2-8124-718a201e98c9', 'name': 'Корреспондент - Технології', 'url': 'http://k.img.com.ua/rss/ua/technews.xml', 'type': 'RSS', 'active': True, 'schedule': '*/30 * * * *', 'lastParsedAt': '2026-04-21T12:44:25.032576Z', 'nextRunAt': '2026-04-21T13:00:00Z', 'logoUrl': 'http://news.img.com.ua/img/smalllogo.gif', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:44:25.032576Z'}, {'id': '32fc80a2-49b5-4438-8856-3265fa694415', 'name': 'Уніан - Технології', 'url': 'https://www.unian.ua/techno', 'type': 'HTML', 'active': True, 'schedule': '14 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.450488Z', 'nextRunAt': '2026-04-21T13:14:00Z', 'logoUrl': 'https://www.unian.ua/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:49:35.450488Z'}, {'id': '6a6a7089-f335-4b97-a414-6a50f7321738', 'name': 'УНН - Технології', 'url': 'https://unn.ua/rss/tech_uk.xml', 'type': 'RSS', 'active': True, 'schedule': '8 * * * *', 'lastParsedAt': '2026-04-21T12:45:38.888004Z', 'nextRunAt': '2026-04-21T13:08:00Z', 'logoUrl': 'https://unn.ua/social_logo.jpg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:38.888004Z'}, {'id': '7c36f32a-b163-4a79-b2ff-ab0f0af0be04', 'name': 'Корреспондент - Технології', 'url': 'http://k.img.com.ua/rss/ua/science.xml', 'type': 'RSS', 'active': True, 'schedule': '12 * * * *', 'lastParsedAt': '2026-04-21T12:45:56.035464Z', 'nextRunAt': '2026-04-21T13:12:00Z', 'logoUrl': 'http://news.img.com.ua/img/smalllogo.gif', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:56.035464Z'}, {'id': 'ac0d884a-c7e4-45ae-ad6c-63a74c87cb75', 'name': 'Главком - Технології', 'url': 'https://glavcom.ua/techno.html', 'type': 'HTML', 'active': True, 'schedule': '7 * * * *', 'lastParsedAt': '2026-04-21T12:45:32.811433Z', 'nextRunAt': '2026-04-21T13:07:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:39:31.3177Z', 'updatedAt': '2026-04-21T12:45:32.811433Z'}, {'id': 'f9ebcfd7-814d-48aa-9eaf-c86b92e21fb1', 'name': 'ТСН - Технології', 'url': 'https://tsn.ua/nauka_it', 'type': 'HTML', 'active': True, 'schedule': '7 */1 * * *', 'lastParsedAt': '2026-04-21T12:45:32.885748Z', 'nextRunAt': '2026-04-21T13:07:00Z', 'logoUrl': 'https://tsn.ua/favicon.svg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:32.885748Z'}, {'id': 'fc56db2b-c7b0-4b72-a4bd-55a97c5bf8ce', 'name': 'Obozrevatel - Технології', 'url': 'https://news.obozrevatel.com/ukr/tech/', 'type': 'HTML', 'active': True, 'schedule': '16 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.281044Z', 'nextRunAt': '2026-04-21T13:16:00Z', 'logoUrl': 'https://cdn.obozrevatel.com/news/img/favicons/favicon.ico', 'createdAt': '2026-04-16T20:04:09.734554Z', 'updatedAt': '2026-04-21T12:49:35.281044Z'}], 'totalCount': 8, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Технології оброблена: 8 нових джерел
{'data': [{'id': '1eaa2f80-6967-48b4-80f1-27bf9d1691eb', 'name': 'Obozrevatel - Наука', 'url': 'https://news.obozrevatel.com/ukr/nauka/', 'type': 'HTML', 'active': True, 'schedule': '23 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.808044Z', 'nextRunAt': '2026-04-21T13:23:00Z', 'logoUrl': 'https://cdn.obozrevatel.com/news/img/favicons/favicon.ico', 'createdAt': '2026-04-16T20:06:02.905325Z', 'updatedAt': '2026-04-21T12:49:35.808044Z'}, {'id': '56ed9141-0fd0-4f91-ade2-f0d8abb8a7f6', 'name': 'Корреспондент - Наука', 'url': 'http://k.img.com.ua/rss/ua/tech.xml', 'type': 'RSS', 'active': True, 'schedule': '10 * * * *', 'lastParsedAt': '2026-04-21T12:45:50.984402Z', 'nextRunAt': '2026-04-21T13:10:00Z', 'logoUrl': 'http://news.img.com.ua/img/smalllogo.gif', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:45:50.984402Z'}, {'id': 'e18b0739-6499-4a75-a6db-113113a5b9db', 'name': '24 канал - Наука', 'url': 'https://24tv.ua/education/nauka-v-ukrayini_tag7194/', 'type': 'HTML', 'active': True, 'schedule': '20 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.515989Z', 'nextRunAt': '2026-04-21T13:20:00Z', 'logoUrl': 'https://24tv.ua/assets/sites/education/favicon.ico', 'createdAt': '2026-04-16T13:49:27.046472Z', 'updatedAt': '2026-04-21T12:49:35.515989Z'}, {'id': 'feceeaaf-8840-4abe-ba92-46ef79478b7c', 'name': 'Уніан - Наука', 'url': 'https://www.unian.ua/science', 'type': 'HTML', 'active': True, 'schedule': '12 * * * *', 'lastParsedAt': '2026-04-21T12:46:00.063289Z', 'nextRunAt': '2026-04-21T13:12:00Z', 'logoUrl': 'https://www.unian.ua/favicon.ico', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:46:00.063289Z'}], 'totalCount': 4, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Наука оброблена: 4 нових джерел
{'data': [{'id': '7f1802ce-c04b-4615-bcb4-11dfa8fb48ea', 'name': '24 канал - Освіта', 'url': 'https://24tv.ua/education/osvita-v-ukrayini_tag7093/', 'type': 'HTML', 'active': True, 'schedule': '18 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.337402Z', 'nextRunAt': '2026-04-21T13:18:00Z', 'logoUrl': 'https://24tv.ua/assets/sites/education/favicon.ico', 'createdAt': '2026-04-16T13:48:35.470093Z', 'updatedAt': '2026-04-21T12:49:35.337402Z'}, {'id': '9469aa98-da2f-4b40-b98d-db991ca85f51', 'name': 'УНН - Освіта', 'url': 'https://unn.ua/rss/education_uk.xml', 'type': 'RSS', 'active': True, 'schedule': '16 * * * *', 'lastParsedAt': '2026-04-21T12:49:35.227297Z', 'nextRunAt': '2026-04-21T13:16:00Z', 'logoUrl': 'https://unn.ua/social_logo.jpg', 'createdAt': '2026-04-16T12:01:13.71219Z', 'updatedAt': '2026-04-21T12:49:35.227297Z'}, {'id': 'c1e5a983-db3d-4236-951f-110c11c588f4', 'name': 'Главком - Освіта', 'url': 'https://glavcom.ua/country/science.html', 'type': 'HTML', 'active': True, 'schedule': '12 * * * *', 'lastParsedAt': '2026-04-21T12:45:58.047863Z', 'nextRunAt': '2026-04-21T13:12:00Z', 'logoUrl': 'https://glavcom.ua/user/img/favicon.ico', 'createdAt': '2026-04-16T18:41:56.257243Z', 'updatedAt': '2026-04-21T12:45:58.047863Z'}], 'totalCount': 3, 'totalPages': 1, 'page': 1, 'pageSize': 20}
Категорія Освіта оброблена: 3 нових джерел

In [30]:
df['category'] = df['source_id'].map(category_mapping)
df.head()

,title,description,link,image_url,published_at,source_id,category
0,росіяни вночі вдарили по Дніпру балістикою є п...,росіяни вночі вдарили по Дніпру балістикою є п...,https://unn.ua/news/rosiiany-vnochi-vdaryly-po...,https://unn.ua/img/2026/04/16/1776300112-1832-...,2026-04-16T00:41:56Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1,Війна
1,"Інфантіно заявив, що Іран візьме участь у чемп...","Інфантіно заявив, що Іран візьме участь у чемп...",https://unn.ua/news/infantino-zaiavyv-shcho-ir...,https://unn.ua/img/2026/04/15/1776293154-1132-...,2026-04-15T22:45:57Z,8fbd6207-4ebc-4b96-93c8-8197ee3925e1,Спорт
2,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,https://unn.ua/news/ataky-rf-na-dnipro-15-kvit...,https://unn.ua/img/2026/04/15/1776252519-2000-...,2026-04-15T11:28:42Z,9469aa98-da2f-4b40-b98d-db991ca85f51,Освіта
3,Amazon представила авіаційну антену супутников...,Антена на літаку дає доступ до альтернативи St...,https://ua.korrespondent.net/tech/technews/487...,https://kor.ill.in.ua/m/190x120/4402706.jpg,2026-04-14T12:57:00Z,1f37bd0e-7185-48e2-8124-718a201e98c9,Технології
4,"""Українська бронетехніка"" модернізує ударні др...","""Українська бронетехніка"" модернізує ударні др...",https://unn.ua/news/ukrainska-bronetekhnika-mo...,https://unn.ua/img/2026/04/15/1776292651-3940-...,2026-04-15T22:37:33Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1,Війна

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7754 entries, 0 to 7753
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         7754 non-null   str
 1   description   7754 non-null   str
 2   link          7754 non-null   str
 3   image_url     6180 non-null   str
 4   published_at  7749 non-null   str
 5   source_id     7754 non-null   str
 6   category      5489 non-null   str
dtypes: str(7)
memory usage: 424.2 KB

In [32]:
df.category.value_counts()

category
Війна         1224
Політика      1069
Економіка      951
Спорт          848
Технології     362
Культура       347
Здоров'я       313
Наука          148
Освіта         130
Туризм          97
Name: count, dtype: int64

In [33]:
df[df.description.str.contains('<')].groupby('source_id').first().description.to_numpy()

array(['Бразильський президент Лула підтримав Папу Лева після критики Трампа<p>Президент Бразилії висловив солідарність понтифіку через його заклики до миру. Трамп назвав Папу слабким після слів про\nнеприпустимість ударів по Ірану.</p>',
       'Рада розгляне ініціативу щодо зміни порядку та строків сплати штрафів, зафіксованих камерами автофіксації<p>Законопроєкт № 13614 пропонує збільшити термін добровільної оплати до 15 днів. Час на передачу постанови до примусового виконання\nзросте до 3 місяців.</p>',
       'США розширили санкції проти мережі іранського нафтового магната, щоб тиснути на Тегеран<p>Вашингтон запровадив обмеження проти компаній та суден за тіньовий експорт нафти. Санкції стосуються схем відмивання коштів через\nзолото Венесуели.</p>',
       "В Україні готують державну політику з промоції читання - розпочинають з національного дослідження<p>Міністерство культури вивчить мотивацію та бар'єри українців у читанні для формування державної політики. Результати оприлюднять\nнавесні 2026 року.</p>",
       '"Українська бронетехніка" модернізує ударні дрони та впроваджує автодонаведення<p>Компанія модернізує БпЛА UB60D бойовими частинами на базі мін та модулем автонаведення. Виробництво дозволяє випускати до 20 тисяч\nдронів на місяць.</p>',
       "росіяни вночі вдарили по Дніпру балістикою є поранені та руйнування<p>росіяни поцілили у житлові квартали Дніпра, пошкодивши багатоповерхівку та приватний будинок. Постраждали п'ятеро людей, одна жінка у важкому стані.</p>",
       'Інфантіно заявив, що Іран візьме участь у чемпіонаті світу з футболу попри війну<p>Президент ФІФА заявив про допуск Ірану до чемпіонату світу через проходження кваліфікації. Команда проведе матчі групового етапу в\nКаліфорнії та Сіетлі.</p>',
       'Інфантіно заявив, що Іран візьме участь у чемпіонаті світу з футболу попри війну<p>Президент ФІФА заявив про допуск Ірану до чемпіонату світу через проходження кваліфікації. Команда проведе матчі групового етапу в\nКаліфорнії та Сіетлі.</p>',
       'Атаки рф на Дніпро 15 квітня - пошкодежно три вищі навчальні заклади<p>Внаслідок атаки 15 квітня пошкоджено три виші Дніпра, є двоє поранених. Всі вищезазначені навчальні заклади перебувають неподалік\nодин одного.</p>',
       'Пацієнти проти системи: чому люди бояться судитись з приватними клініками<p>Справи про медичну недбалість в Україні рідко доходять до суду попри скарги пацієнтів і заяви в правоохоронні органи. Причиною\nцьому можуть бути: висока вартість судових процесів, складність доведення лікарської помилки, а також брак доказів через те, що\nпацієнту рідко видають всю медичну документацію на руки. Тож нерівність ресурсів між пацієнтами та приватними клініками часто\nзмушують людей відмовлятися від боротьби.</p>'],
      dtype=object)

In [34]:
import sys

PROJECT_ROOT = os.path.abspath('..')
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from analyzer.preprocessing import html_sanitize

html_sanitize

In [35]:
df['title'] = df['title'].map(html_sanitize)
df['description'] = df['description'].map(html_sanitize)
df.head()

,title,description,link,image_url,published_at,source_id,category
0,росіяни вночі вдарили по Дніпру балістикою є п...,росіяни вночі вдарили по Дніпру балістикою є п...,https://unn.ua/news/rosiiany-vnochi-vdaryly-po...,https://unn.ua/img/2026/04/16/1776300112-1832-...,2026-04-16T00:41:56Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1,Війна
1,"Інфантіно заявив, що Іран візьме участь у чемп...","Інфантіно заявив, що Іран візьме участь у чемп...",https://unn.ua/news/infantino-zaiavyv-shcho-ir...,https://unn.ua/img/2026/04/15/1776293154-1132-...,2026-04-15T22:45:57Z,8fbd6207-4ebc-4b96-93c8-8197ee3925e1,Спорт
2,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,Атаки рф на Дніпро 15 квітня - пошкодежно три ...,https://unn.ua/news/ataky-rf-na-dnipro-15-kvit...,https://unn.ua/img/2026/04/15/1776252519-2000-...,2026-04-15T11:28:42Z,9469aa98-da2f-4b40-b98d-db991ca85f51,Освіта
3,Amazon представила авіаційну антену супутников...,Антена на літаку дає доступ до альтернативи St...,https://ua.korrespondent.net/tech/technews/487...,https://kor.ill.in.ua/m/190x120/4402706.jpg,2026-04-14T12:57:00Z,1f37bd0e-7185-48e2-8124-718a201e98c9,Технології
4,"""Українська бронетехніка"" модернізує ударні др...","""Українська бронетехніка"" модернізує ударні др...",https://unn.ua/news/ukrainska-bronetekhnika-mo...,https://unn.ua/img/2026/04/15/1776292651-3940-...,2026-04-15T22:37:33Z,6cdf1e5f-0fc7-48b1-a797-126f96b330d1,Війна

In [36]:
df[df.description.str.contains('<')]['source_id'].value_counts()

Series([], Name: count, dtype: int64)

In [37]:
df[df.description.str.contains('<')].description.to_numpy()

array([], dtype=object)

In [38]:
df.description[0], df.title[0]

("росіяни вночі вдарили по Дніпру балістикою є поранені та руйнування. росіяни поцілили у житлові квартали Дніпра, пошкодивши багатоповерхівку та приватний будинок. Постраждали п'ятеро людей, одна жінка у важкому стані.",
 'росіяни вночі вдарили по Дніпру балістикою є поранені та руйнування')

In [39]:
# 1. Підготовка даних
# Відкидаємо рядки, де категорія NaN
ml_df = df.dropna(subset=['category']).copy()

# Об'єднуємо заголовок та опис для кращого контексту
ml_df['text'] = ml_df['title'] + " " + ml_df['description']

print(f"Кількість новин для тренування: {len(ml_df)}")
ml_df[['text', 'category']].head()

Кількість новин для тренування: 5489

                                                text    category
0  росіяни вночі вдарили по Дніпру балістикою є п...       Війна
1  Інфантіно заявив, що Іран візьме участь у чемп...       Спорт
2  Атаки рф на Дніпро 15 квітня - пошкодежно три ...      Освіта
3  Amazon представила авіаційну антену супутников...  Технології
4  "Українська бронетехніка" модернізує ударні др...       Війна

In [40]:
# 2. Стратифіковане розбиття вибірки
from sklearn.model_selection import train_test_split

X = ml_df['text']
y = ml_df['category']

# Використовуємо stratify=y для збереження пропорцій незбалансованих класів
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Тренувальна вибірка: {len(X_train)}")
print(f"Тестова вибірка: {len(X_test)}")

Тренувальна вибірка: 4391
Тестова вибірка: 1098

In [41]:
# 3. Створення та навчання Pipeline (TF-IDF + LinearSVC)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

# Пайплайн автоматично векторизує текст і подає на вхід класифікатору
text_clf = Pipeline([
    ('tfidf', TfidfVectorizer(max_df=0.8, min_df=2, ngram_range=(1, 2))),
    ('clf', LinearSVC(random_state=42, C=0.1, class_weight='balanced'))
])

text_clf.fit(X_train, y_train)
print("Модель успішно натренована!")

Модель успішно натренована!

In [42]:
# 4. Оцінка якості
from sklearn.metrics import classification_report, accuracy_score

predictions = text_clf.predict(X_test)

print(f"Загальна точність (Accuracy): {accuracy_score(y_test, predictions):.3f}\n")
print(classification_report(y_test, predictions))

Загальна точність (Accuracy): 0.730

              precision    recall  f1-score   support

       Війна       0.80      0.75      0.77       245
   Економіка       0.74      0.72      0.73       190
    Здоров'я       0.79      0.79      0.79        63
    Культура       0.57      0.72      0.64        69
       Наука       0.45      0.60      0.51        30
      Освіта       0.56      0.73      0.63        26
    Політика       0.68      0.72      0.70       214
       Спорт       0.94      0.86      0.90       170
  Технології       0.51      0.43      0.47        72
      Туризм       0.73      0.58      0.65        19

    accuracy                           0.73      1098
   macro avg       0.68      0.69      0.68      1098
weighted avg       0.74      0.73      0.73      1098

In [43]:
# 5. Збереження моделі у файл
import joblib

# Зберігаємо у кореневу папку проєкту для використання в сервісі
model_path = os.path.join(PROJECT_ROOT, 'news_categorization_model.joblib')
joblib.dump(text_clf, model_path)

print(f"Модель збережено за шляхом: {model_path}")

Модель збережено за шляхом: /home/andrii/University/news-aggregator/news-analyzer/news_categorization_model.joblib

## Дослідження найкращої конфігурації (Grid Search)

Ми використаємо `GridSearchCV`, щоб перевірити різні комбінації параметрів:
1. **TF-IDF**: розмір біграм, максимальна частота слів.
2. **LinearSVC**: параметр регуляризації `C` та метод обробки незбалансованих класів.

In [44]:
from sklearn.model_selection import GridSearchCV

# Визначаємо сітку параметрів
param_grid = {
    'tfidf__max_df': [0.8, 0.9, 1.0],
    'tfidf__min_df': [1, 2, 3],
    'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)], # тільки слова або слова + біграми
    'clf__C': [0.1, 1, 10, 100],
    'clf__class_weight': [None, 'balanced'] # балансування ваг для рідкісних категорій
}

# Створюємо GridSearchCV
# cv=5: 5-кратна крос-валідація
# scoring='f1_weighted': метрика, що найкраще підходить для незбалансованих даних
grid_search = GridSearchCV(
    text_clf, 
    param_grid, 
    cv=5, 
    n_jobs=-1, 
    scoring='f1_weighted', 
    verbose=2
)

print("Починаю пошук оптимальних параметрів... (це може зайняти час)")
grid_search.fit(X_train, y_train)

print(f"\nНайкращий F1-weighted score: {grid_search.best_score_:.4f}")
print("Найкращі параметри:", grid_search.best_params_)

Починаю пошук оптимальних параметрів... (це може зайняти час)
Fitting 5 folds for each of 216 candidates, totalling 1080 fits

[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   2.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   2.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   2.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   2.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   2.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   1.0s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.9s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.8s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.5s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.7s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   0.8s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.2s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.3s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.4s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   0.6s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.5s
[CV] END clf__C=0.1, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=   1.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  12.0s
[CV] END clf__C=10, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  12.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END clf__C=10, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  12.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END clf__C=10, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  13.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END clf__C=10, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.4s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   9.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.4s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  14.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  14.4s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  14.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  16.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.8s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.8s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   7.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   9.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   9.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.8s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   0.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   3.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   3.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.8s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  14.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  14.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  16.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   0.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  17.5s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.4s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   8.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   1.7s[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   9.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=   9.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.7s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   0.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   2.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   3.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   3.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.6s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   1.9s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.1s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.0s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  13.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.2s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.3s
[CV] END clf__C=10, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  15.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.8s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   5.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.7s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.7s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  18.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   6.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  20.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  20.8s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   2.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  20.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   4.9s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.0s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.4s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.7s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   4.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   4.1s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.3s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   2.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  34.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  37.7s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  37.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  37.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  39.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.2s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  19.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  19.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.0s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.8s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   5.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  23.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.8s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   4.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.0s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.7s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.1s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.0s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.5s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  35.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  36.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  36.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  37.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  39.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  18.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  19.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   5.3s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  24.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  24.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  24.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.3s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.3s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.0s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.4s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   8.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.6s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   4.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.9s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  33.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.2s
[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  36.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  34.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  38.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=None, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  40.8s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   3.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   3.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.0s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   6.0s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  22.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  23.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  22.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   3.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.3s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.4s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   4.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.0s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.2s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.3s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   4.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.7s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.8s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  35.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  36.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  38.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  38.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  40.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.2s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   5.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  23.0s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  22.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.8s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   3.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.2s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.5s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.8s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   1.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.8s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.1s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   4.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   3.7s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  34.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  36.3s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 1); total time=   5.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  38.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  39.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=0.9, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  41.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.8s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   1.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 1); total time=   2.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  22.3s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   5.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  21.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  23.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  22.6s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 2); total time=  23.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   3.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   4.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 2); total time=   6.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.5s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   7.0s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   5.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   1.9s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=2, tfidf__ngram_range=(1, 3); total time=   6.6s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 1); total time=   2.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.2s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.3s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   3.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 2); total time=   2.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.6s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.1s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.4s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   2.9s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=3, tfidf__ngram_range=(1, 3); total time=   3.1s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  33.2s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  34.0s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  34.4s
[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  30.7s

/home/andrii/University/news-aggregator/news-analyzer/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV] END clf__C=100, clf__class_weight=balanced, tfidf__max_df=1.0, tfidf__min_df=1, tfidf__ngram_range=(1, 3); total time=  33.9s

Найкращий F1-weighted score: 0.7421
Найкращі параметри: {'clf__C': 1, 'clf__class_weight': 'balanced', 'tfidf__max_df': 0.8, 'tfidf__min_df': 1, 'tfidf__ngram_range': (1, 1)}

In [45]:
# Оцінка найкращої моделі на тестовій вибірці
best_model = grid_search.best_estimator_
best_predictions = best_model.predict(X_test)

print("Звіт по найкращій моделі з Grid Search:\n")
print(classification_report(y_test, best_predictions))

# Збереження найкращої моделі
final_model_path = os.path.join(PROJECT_ROOT, 'news_categorization_model_optimized.joblib')
joblib.dump(best_model, final_model_path)
print(f"Оптимізовану модель збережено: {final_model_path}")

Звіт по найкращій моделі з Grid Search:

              precision    recall  f1-score   support

       Війна       0.77      0.76      0.76       245
   Економіка       0.73      0.80      0.76       190
    Здоров'я       0.84      0.84      0.84        63
    Культура       0.62      0.77      0.69        69
       Наука       0.44      0.37      0.40        30
      Освіта       0.59      0.65      0.62        26
    Політика       0.70      0.68      0.69       214
       Спорт       0.96      0.91      0.93       170
  Технології       0.55      0.49      0.51        72
      Туризм       0.82      0.47      0.60        19

    accuracy                           0.74      1098
   macro avg       0.70      0.67      0.68      1098
weighted avg       0.74      0.74      0.74      1098

Оптимізовану модель збережено: /home/andrii/University/news-aggregator/news-analyzer/news_categorization_model_optimized.joblib

In [46]:
test_df = ml_df[['text', 'category']]
test_df

                                                   text    category
0     росіяни вночі вдарили по Дніпру балістикою є п...       Війна
1     Інфантіно заявив, що Іран візьме участь у чемп...       Спорт
2     Атаки рф на Дніпро 15 квітня - пошкодежно три ...      Освіта
3     Amazon представила авіаційну антену супутников...  Технології
4     "Українська бронетехніка" модернізує ударні др...       Війна
...                                                 ...         ...
7745  Дюбуа попередив Вордлі перед боєм: Зараз наста...       Спорт
7747  НХЛ: Кароліна не залишає шансів Оттаві Пропону...       Спорт
7748  НБА: Клівленд та Атланта крокують далі Заверши...       Спорт
7751  Участь Алькараса в Ролан Гаррос-2026 під питан...       Спорт
7752  МЮ знайшов гравця на заміну зірковому бразильц...       Спорт

[5489 rows x 2 columns]

In [47]:
test_df['predicted'] = best_model.predict(test_df['text'])
test_df.head()

                                                text    category   predicted
0  росіяни вночі вдарили по Дніпру балістикою є п...       Війна       Війна
1  Інфантіно заявив, що Іран візьме участь у чемп...       Спорт       Спорт
2  Атаки рф на Дніпро 15 квітня - пошкодежно три ...      Освіта      Освіта
3  Amazon представила авіаційну антену супутников...  Технології  Технології
4  "Українська бронетехніка" модернізує ударні др...       Війна  Технології

In [48]:
test_df.text[2], test_df.predicted[2]

('Атаки рф на Дніпро 15 квітня - пошкодежно три вищі навчальні заклади Атаки рф на Дніпро 15 квітня - пошкодежно три вищі навчальні заклади. Внаслідок атаки 15 квітня пошкоджено три виші Дніпра, є двоє поранених. Всі вищезазначені навчальні заклади перебувають неподалік один одного.',
 'Освіта')

In [49]:
errors_df = test_df[test_df.predicted != test_df.category]
errors_df

,text,category,predicted
4,"""Українська бронетехніка"" модернізує ударні др...",Війна,Технології
26,Amazon оголосила дату запуску свого конкурента...,Технології,Культура
47,Україна змінює підхід до підготовки кадрів - в...,Освіта,Економіка
51,Хакери могли зламати поштові скриньки українсь...,Війна,Технології
53,Підтверджено рішення про нові внески в програм...,Війна,Політика
...,...,...,...
7710,"BWS 2026 «Бізнеси сміливих»: ключові виклики, ...",Здоров'я,Освіта
7711,"BWS 2026 «Бізнеси сміливих»: ключові виклики, ...",Культура,Освіта
7712,Смартгодинник може вводити в оману: чому це ві...,Технології,Здоров'я
7721,Росія в ООН назвала українців «витратним матер...,Політика,Війна
7730,"BWS 2026 «Бізнеси сміливих»: ключові виклики, ...",Політика,Освіта